<?php

use Illuminate\Database\Seeder;

class CmsSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cms_settings')->delete();
        
        \DB::table('cms_settings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'login_background_color',
            'content' => 'radial-gradient(circle,#4070fa, #000032);',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Input hexacode',
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Estilo de página de registro',
                'label' => 'Login Background Color',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'login_font_color',
                'content' => NULL,
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Input hexacode',
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Estilo de página de registro',
                'label' => 'Login Font Color',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'login_background_image',
                'content' => NULL,
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Estilo de página de registro',
                'label' => 'Login Background Image',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'email_sender',
                'content' => 'server@paymark8.com',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Correo',
                'label' => 'Email Sender',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'smtp_driver',
                'content' => 'smtp',
                'content_input_type' => 'select',
                'dataenum' => 'smtp,mail,sendmail',
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Correo',
                'label' => 'Mail Driver',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'smtp_host',
                'content' => 'smtp.zoho.com',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Correo',
                'label' => 'SMTP Host',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'smtp_port',
                'content' => '465',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'default 25',
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Correo',
                'label' => 'SMTP Port',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'smtp_username',
                'content' => 'server@paymark8.com',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Correo',
                'label' => 'SMTP Username',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'smtp_password',
                'content' => 'Quaira2019@',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Correo',
                'label' => 'SMTP Password',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'appname',
                'content' => 'Paymark8',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Aplicaciones',
                'label' => 'Application Name',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'default_paper_size',
                'content' => 'Legal',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Paper size, ex : A4, Legal, etc',
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Aplicaciones',
                'label' => 'Default Paper Print Size',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'logo',
                'content' => 'uploads/2020-05/4bacba3ce5f56a46d0dc25bcf5a8dc2e.png',
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Aplicaciones',
                'label' => 'Logo',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'favicon',
                'content' => NULL,
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Aplicaciones',
                'label' => 'Favicon',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'api_debug_mode',
                'content' => 'true',
                'content_input_type' => 'select',
                'dataenum' => 'true,false',
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Aplicaciones',
                'label' => 'API Debug Mode',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'google_api_key',
                'content' => NULL,
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Aplicaciones',
                'label' => 'Google API Key',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'google_fcm_key',
                'content' => NULL,
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-09-11 13:10:07',
                'updated_at' => NULL,
                'group_setting' => 'Ajustes de Aplicaciones',
                'label' => 'Google FCM Key',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'oficina_video_youtube',
                'content' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/0RmPZprOTFg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Video de Youtube que ira en la oficina',
                'created_at' => '2019-08-09 19:18:03',
                'updated_at' => NULL,
                'group_setting' => 'Oficina',
                'label' => 'Video en la Oficina',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'boton_paypal',
            'content' => '<html><body><a target="_blank" href="https://www.visanetlink.pe/pagoseguro/PAYMARK8/298964"><button style="padding: 10px 16px; line-height: 1.3333333; border-radius: 6px;  -moz-border-radius: 5px;   -webkit-border-radius: 5px; color: #fff;font-weight: bold; font-style: normal; background-color: rgb(255, 206, 28);">COMPRAR</button></a></body></html>',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Obten el codigo del boton ingresando a la cuenta de tu comercio',
                'created_at' => '2019-08-09 19:18:03',
                'updated_at' => '2019-12-18 19:38:11',
                'group_setting' => 'Ajustes de Aplicaciones',
                'label' => 'Boton para pago en línea',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'facebook',
                'content' => NULL,
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'URL Facebook',
                'created_at' => '2019-08-09 19:18:03',
                'updated_at' => NULL,
                'group_setting' => 'Sociales',
                'label' => 'Facebook',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'instagram',
                'content' => NULL,
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'URL Instagram',
                'created_at' => '2019-08-09 19:18:03',
                'updated_at' => NULL,
                'group_setting' => 'Sociales',
                'label' => 'Instagram',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'correo',
                'content' => 'soporte@paymark8.com',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Correo',
                'created_at' => '2019-08-09 19:18:03',
                'updated_at' => NULL,
                'group_setting' => 'Contacto',
                'label' => 'Correo',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'whatsapp',
                'content' => NULL,
                'content_input_type' => 'text',
                'dataenum' => NULL,
            'helper' => 'Número acompañado del cídigo del país (ej. +519988456)',
                'created_at' => '2019-08-09 19:18:03',
                'updated_at' => NULL,
                'group_setting' => 'Contacto',
                'label' => 'Whatsapp',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'slider_1',
                'content' => 'uploads/2019-09/dc537db331b803622917be99462589d4.jpg',
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-08-09 19:18:03',
                'updated_at' => NULL,
                'group_setting' => 'Sliders',
                'label' => 'Slider_1',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'slider_2',
                'content' => NULL,
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-08-09 19:18:03',
                'updated_at' => NULL,
                'group_setting' => 'Sliders',
                'label' => 'Slider 2',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'slider_3',
                'content' => NULL,
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2019-08-09 19:18:03',
                'updated_at' => NULL,
                'group_setting' => 'Sliders',
                'label' => 'Slider 3',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'imagen_popup',
                'content' => 'uploads/2019-12/e890c03950544decbc2a7b88d9098ce5.png',
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => 'Es la imagen que carga al inicar la Página como popup',
                'created_at' => '2019-08-09 19:18:03',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Imagen del Popup',
            ),
            26 => 
            array (
                'id' => 28,
                'name' => 'correo_consultas',
                'content' => NULL,
                'content_input_type' => 'email',
                'dataenum' => NULL,
                'helper' => 'El correo al cual quieres que lleguen las consultas de Paymark8',
                'created_at' => '2019-12-16 15:36:50',
                'updated_at' => NULL,
                'group_setting' => 'Oficina',
                'label' => 'Correo para Recepción de Consultas',
            ),
            27 => 
            array (
                'id' => 29,
                'name' => 'annual_membership_amount',
                'content' => '59',
                'content_input_type' => 'number',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-06 15:45:36',
                'updated_at' => '2020-01-06 15:45:36',
                'group_setting' => 'afiliacion',
                'label' => 'Precio Anual de Afiliacion',
            ),
            28 => 
            array (
                'id' => 30,
                'name' => 'monthly_membership_amount',
                'content' => '6',
                'content_input_type' => 'number',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-06 15:45:36',
                'updated_at' => '2020-01-06 15:45:36',
                'group_setting' => 'afiliacion',
                'label' => 'Precio Mensual de Afiliacion',
            ),
            29 => 
            array (
                'id' => 31,
                'name' => 'invoice',
                'content' => '200054',
                'content_input_type' => 'number',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-06 15:45:36',
                'updated_at' => '2020-01-06 15:45:36',
                'group_setting' => 'visanet',
                'label' => 'Numero base de compra',
            ),
            30 => 
            array (
                'id' => 32,
                'name' => 'api_authorization_url',
                'content' => 'https://apitestenv.vnforapps.com/api.authorization/v3/authorization/ecommerce/',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-06 15:45:36',
                'updated_at' => '2020-01-06 15:45:36',
                'group_setting' => 'visanet',
                'label' => 'Url Api authorización',
            ),
            31 => 
            array (
                'id' => 33,
                'name' => 'api_security_url',
                'content' => 'https://apitestenv.vnforapps.com/api.security/v1/security',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-06 15:45:36',
                'updated_at' => '2020-01-06 15:45:36',
                'group_setting' => 'visanet',
                'label' => 'Url Api seguridad',
            ),
            32 => 
            array (
                'id' => 34,
                'name' => 'api_url',
                'content' => 'https://apitestenv.vnforapps.com/api.ecommerce/v2/ecommerce/token/session/',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-06 15:45:36',
                'updated_at' => '2020-01-06 15:45:36',
                'group_setting' => 'visanet',
                'label' => 'Url Api',
            ),
            33 => 
            array (
                'id' => 35,
                'name' => 'script_url',
                'content' => 'https://static-content-qas.vnforapps.com/v2/js/checkout.js?qa=true',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-06 15:45:36',
                'updated_at' => '2020-01-06 15:45:36',
                'group_setting' => 'visanet',
                'label' => 'Url script url',
            ),
            34 => 
            array (
                'id' => 36,
                'name' => 'merchant_id',
                'content' => '115015006',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-06 15:45:36',
                'updated_at' => '2020-01-06 15:45:36',
                'group_setting' => 'visanet',
                'label' => 'Merchant Id',
            ),
            35 => 
            array (
                'id' => 37,
                'name' => 'user',
                'content' => 'integraciones.visanet@necomplus.com',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-06 15:45:36',
                'updated_at' => '2020-01-06 15:45:36',
                'group_setting' => 'visanet',
                'label' => 'Usuario',
            ),
            36 => 
            array (
                'id' => 38,
                'name' => 'password',
                'content' => 'd5e7nk$M',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-06 15:45:36',
                'updated_at' => '2020-01-06 15:45:36',
                'group_setting' => 'visanet',
                'label' => 'Contraseña',
            ),
            37 => 
            array (
                'id' => 39,
                'name' => 'currency_visanet',
                'content' => 'USD',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-10 20:04:56',
                'updated_at' => '2020-01-10 20:04:56',
                'group_setting' => 'visanet',
                'label' => 'Moneda de procesamiento',
            ),
            38 => 
            array (
                'id' => 40,
                'name' => 'logo_checkout',
                'content' => 'uploads/2020-01/13d98cfa205a999f98758dd08d2930ba.jpg',
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'visanet',
                'label' => 'Logo que se usará en popup de procesar el pago',
            ),
            39 => 
            array (
                'id' => 41,
                'name' => 'section_1_header',
                'content' => '¿QUIÉNES SOMOS?',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Título 1',
            ),
            40 => 
            array (
                'id' => 42,
                'name' => 'section_1_content',
                'content' => '<p>Un gran equipo comprometido con brindar una nueva experiencia de compra para nuestros clientes y alcanzar la mayor audiencia referenciados por los mismos.</p>',
                'content_input_type' => 'wysiwyg',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Contenido 1',
            ),
            41 => 
            array (
                'id' => 43,
                'name' => 'section_1_image',
                'content' => 'uploads/2020-05/e0282bcbeacd4f7356076f8d205dab5a.jpg',
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Imagen 1',
            ),
            42 => 
            array (
                'id' => 44,
                'name' => 'section_2_header',
                'content' => '¿QUÉ TE OFRECEMOS?',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Título 2',
            ),
            43 => 
            array (
                'id' => 45,
                'name' => 'section_2_content',
                'content' => '<p>Una nueva oportunidad de aprovechar tu activo social desde donde est&eacute;s, a cualquier hora, por compartirnos con m&aacute;s personas, te ayudamos a conseguir ingresos extra.</p>',
                'content_input_type' => 'wysiwyg',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Contenido 2',
            ),
            44 => 
            array (
                'id' => 46,
                'name' => 'section_2_image',
                'content' => 'uploads/2020-05/3160bbe388db61f2559ec893c7b8a4ab.jpg',
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Imagen 2',
            ),
            45 => 
            array (
                'id' => 47,
                'name' => 'section_3_header',
                'content' => NULL,
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Título 3',
            ),
            46 => 
            array (
                'id' => 48,
                'name' => 'section_3_content',
                'content' => NULL,
                'content_input_type' => 'wysiwyg',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Contenido 3',
            ),
            47 => 
            array (
                'id' => 49,
                'name' => 'section_3_image',
                'content' => NULL,
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Imagen 3',
            ),
            48 => 
            array (
                'id' => 50,
                'name' => 'section_4_header',
                'content' => NULL,
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Título 4',
            ),
            49 => 
            array (
                'id' => 51,
                'name' => 'section_4_content',
                'content' => NULL,
                'content_input_type' => 'wysiwyg',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Contenido 4',
            ),
            50 => 
            array (
                'id' => 52,
                'name' => 'section_4_image',
                'content' => 'uploads/2020-05/ea6b26a432d32867c57c69ed70ee2a88.jpg',
                'content_input_type' => 'upload_image',
                'dataenum' => NULL,
                'helper' => NULL,
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Imagen 4',
            ),
            51 => 
            array (
                'id' => 53,
                'name' => 'estadistica_oficina_1',
                'content' => 'Total Histórico de Ganancias: Dólares ganados en vistas y linkers afiliados hasta la fecha.',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Total Histórico de Ganancias: Dólares ganados en vistas y linkers afiliados hasta la fecha.',
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Oficina',
                'label' => 'Estadística Oficina 1',
            ),
            52 => 
            array (
                'id' => 54,
                'name' => 'estadistica_oficina_2',
                'content' => 'Ganancias por Vistas y Linkers afiliados actuales: Dólares ganados desde el último cobro hasta la fecha.',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Ganancias por Vistas y Linkers afiliados actuales: Dólares ganados desde el último cobro hasta la fecha.',
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Oficina',
                'label' => 'Estadística Oficina 2',
            ),
            53 => 
            array (
                'id' => 55,
                'name' => 'estadistica_oficina_3',
                'content' => 'Capacidad de Retiro: 01 Linker afiliado por cada 10 vistas y $20 como mínimo.',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Capacidad de Retiro: 01 Linker afiliado por cada 10 vistas y $20 como mínimo.',
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Oficina',
                'label' => 'Estadística Oficina 3',
            ),
            54 => 
            array (
                'id' => 56,
                'name' => 'estadistica_oficina_4',
                'content' => 'Dólares por Ganar: dólares que ganarías si sólo compartes tu link sin necesidad de afiliar ni un Linker más.',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Dólares por Ganar: dólares que ganarías si sólo compartes tu link sin necesidad de afiliar ni un Linker más.',
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Oficina',
                'label' => 'Estadística Oficina 4',
            ),
            55 => 
            array (
                'id' => 57,
                'name' => 'estadistica_oficina_5',
                'content' => 'Ganancia por Vistas Actuales: Dólares generados por compartir tu link.',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Ganancia por Vistas Actuales: Dólares generados por compartir tu link.',
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Oficina',
                'label' => 'Estadística Oficina 5',
            ),
            56 => 
            array (
                'id' => 58,
                'name' => 'estadistica_oficina_6',
                'content' => 'Ganancia por Linkers Afiliados Actuales',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Ganancia por Linkers Afiliados Actuales',
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Oficina',
                'label' => 'Estadística Oficina 6',
            ),
            57 => 
            array (
                'id' => 59,
                'name' => 'estadistica_oficina_7',
                'content' => 'Dólares por Efectuarse',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Dólares por Efectuarse',
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Oficina',
                'label' => 'Estadística Oficina 7',
            ),
            58 => 
            array (
                'id' => 60,
                'name' => 'estadistica_oficina_8',
                'content' => 'Potencial de retiro por Linkers Indirectos: Mayor capacidad de retiro gracias a los linkers indirectos',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Potencial de retiro por Linkers Indirectos: Mayor capacidad de retiro gracias a los linkers indirectos',
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Oficina',
                'label' => 'Estadística Oficina 8',
            ),
            59 => 
            array (
                'id' => 61,
                'name' => 'cabecera_anuncios',
                'content' => 'Asociados',
                'content_input_type' => 'text',
                'dataenum' => NULL,
                'helper' => 'Cabecera de tus anuncios en la página pública',
                'created_at' => '2020-01-12 14:48:47',
                'updated_at' => NULL,
                'group_setting' => 'Landing',
                'label' => 'Título Sección Anuncios',
            ),
        ));
        
        
    }
}